#name = "newsnow"
#pages_build_output_dir = "dist/output/public"
#compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "news"
database_id = "43095a99-1f89-49c5-8013-a197c4a0c878"
